Astroua/TurbuStat

Examples/jasper/fiducial0_all_noise.pbs, Examples/jasper/fiducial1_all.pbs, Examples/jasper/fiducial1_all_noise.pbs, Examples/jasper/fiducial2_all.pbs, Examples/jasper/fiducial2_all_noise.pbs, Examples/jasper/fiducial3_all.pbs, Examples/jasper/fiducial3_all_noise.pbs, Examples/jasper/fiducial4_all.pbs, Examples/jasper/fiducial4_all_noise.pbs, Examples/jasper/fiducial_comp.pbs, Examples/jasper/fiducial_comp_noise.pbs, Examples/jasper/output_mpi.py, Examples/overall_wrapper.py, turbustat/statistics/vca_vcs/vca_vcs.py, turbustat/statistics/wrapping_function.py
* PBS scripts for all runs on Jasper
* Make rms_noise pass into function for complete wrapper script
* Updated single comparison wrapper to use new reduction class
=> Updates to wrapper API

Examples/jasper/fiducial0_all.pbs, Examples/jasper/fiducial0_all_noise.pbs, Examples/jasper/fiducial1_all.pbs, Examples/jasper/fiducial1_all_noise.pbs, Examples/jasper/fiducial2_all.pbs, Examples/jasper/fiducial2_all_noise.pbs, Examples/jasper/fiducial3_all.pbs, Examples/jasper/fiducial3_all_noise.pbs, Examples/jasper/fiducial4_all.pbs, Examples/jasper/fiducial4_all_noise.pbs, turbustat/statistics/wrapping_function.py
Also objects can be manually cleaned up in the stats wrapper function.
=> Minor changes to MPI runs

Examples/jasper/fiducial0_all.pbs, Examples/jasper/fiducial0_all_noise.pbs, Examples/jasper/fiducial1_all.pbs, Examples/jasper/fiducial1_all_noise.pbs, Examples/jasper/fiducial2_all.pbs, Examples/jasper/fiducial2_all_noise.pbs, Examples/jasper/fiducial3_all.pbs, Examples/jasper/fiducial3_all_noise.pbs, Examples/jasper/fiducial4_all.pbs, Examples/jasper/fiducial4_all_noise.pbs, Examples/jasper/fiducial_comp.pbs, Examples/jasper/fiducial_comp_noise.pbs, Examples/jasper/make_moments.pbs, Examples/jasper/make_moments_noise.pbs, Examples/jasper/output_mpi.py, Examples/jasper/output_mpi_load.py, Examples/jasper/reduce_and_save_moments.py, turbustat/analysis/comparison_plot.py
Largely just updates to the wrapper scripts for parallel comparisons.
Includes scripts to reduce and save the cube moments to avoid recomputing.
Small fix for scaling plots in distance plots.
=> Updates to wrapper scripts

Examples/complete_comparisons.py, turbustat/statistics/cramer/cramer.py, turbustat/tests/test_cramer.py
=> Cramer diff spatial

Examples/analysis_pipeline.py, Examples/effect_plots.py, Examples/jasper/complete_comparisons.py, Examples/noise_validation.r, Examples/signal_validation.r, turbustat/analysis/comparison_plot.py, turbustat/analysis/convert_results.py, turbustat/statistics/delta_variance/delta_variance.py
=> Another delta-variance fix; added analysis pipeline

Examples/jasper/complete_comparisons.py, Examples/jasper/output_mpi.py, Examples/jasper/output_mpi_load.py, turbustat/statistics/__init__.py, turbustat/statistics/statistics_list.py
Provide a single list with all statistics that can be run from ```stats_wrapper```
=> Unify statistic list

.travis.yml, turbustat/data_reduction/make_moments.py, turbustat/tests/_testing_data.py, turbustat/tests/test_make_moments.py
Allows for ```Mask_and_Moments``` to load saved moments.
=> Load saved fits files for moment arrays

turbustat/statistics/tsallis/tsallis.py
Changed name to ```sigma_clip``` to be more clear.
Can adjust this parameter from ```run``` now
=> Call sigma_clip from run

Examples/make_distance_plots.py, turbustat/analysis/comparison_plot.py
Plus a script to reproduce the distance plots in the paper.
=> Adding options to comparison_plot

Examples/jasper/run_all.sh, turbustat/statistics/pdf/compare_pdf.py, turbustat/statistics/statistics_list.py, turbustat/statistics/wrapping_function.py, turbustat/tests/data/GetVals.py, turbustat/tests/test_pdf.py
It's just causing errors. This disables it until it's behaviour is more understood.
=> Disable PDF Anderson Darling

CHANGE.rst, turbustat/statistics/base_pspec2.py, turbustat/statistics/mvc/mvc.py, turbustat/statistics/pspec_bispec/pspec_bispec.py, turbustat/statistics/vca_vcs/vca.py
MVC, Spatial Power Spectrum and VCA differ only in how the 2D power spectrum is computed. All now inherit from the same base class: `StatisticBase_PSpec2D`.
=> Abstract out common code for 2D Power spectra

CHANGE.rst, turbustat/statistics/wrapping_function.py, turbustat/tests/test_wrapper.py
Missed updating the name to `MVC_Distance`.
Added a test for the wrapper function.
=> Fix wrapper

CHANGE.rst, turbustat/data_reduction/_moment_errs.py, turbustat/data_reduction/make_moments.py
* Fixed issue with centroid offset in calculating centroid error
* Only compute the line width array, rather than the second moment since it isn't used
* Generalized moment error functions from [signal-id](https://github.com/radio-astro-tools/signal-id/pull/40)
=> Another moments update

turbustat/statistics/pca/pca.py
There's an edge case where the eigenvectors can end up ever-so-slightly complex due to machine roundoff.
=> Casting of complex eigenvectors

CHANGE.rst, turbustat/statistics/stat_moments/highstatmoments.py
Pass an array of weights into `StatsMoments`.
=> Allow weights for calculating moments

CHANGE.rst, turbustat/statistics/delta_variance/delta_variance.py, turbustat/statistics/dendrograms/dendro_stats.py, turbustat/statistics/pca/pca.py, turbustat/statistics/pspec_bispec/bispec.py, turbustat/statistics/scf/scf.py, turbustat/statistics/stat_moments/highstatmoments.py, turbustat/statistics/threeD_to_twoD.py, turbustat/statistics/wavelets/wavelet_transform.py
=> Add progress bars for long operations

CHANGE.rst, turbustat/simulator/gen_field.py, turbustat/simulator/tests/test_extended_fields.py, turbustat/simulator/tests/test_ppv.py
`make_3dfield` added in #186 wasn't normalized correctly.
=> Correct 3D field normalization

CHANGE.rst, docs/data_requirements.rst, docs/tutorials/statistics/pca_example.rst, turbustat/statistics/base_statistic.py, turbustat/statistics/vca_vcs/slice_thickness.py
Also clarify when units may matter in distance metrics.
=> Add accessing PCA eigvals/imgs in tutorial

.travis.yml, turbustat/statistics/base_pspec2.py, turbustat/statistics/delta_variance/delta_variance.py, turbustat/statistics/scf/scf.py
=> plt.show for all plotting

.travis.yml, README.md, docs/install.rst, turbustat/io/input_base.py, turbustat/moments/make_moments.py, turbustat/statistics/pca/pca.py, turbustat/statistics/vca_vcs/slice_thickness.py, turbustat/tests/test_pca.py
* The docs list spectral-cube as an optional dependency but it is currently imported on install. Make it an optional dependency again
* Implement PCA fitting limits from #209
=> Check spectral-cube version

turbustat/statistics/base_pspec2.py
=> Clean up warnings for round power spectrum with fixed ellipticity
