- turbustat/statistics/pca/pca.py
Forgot this one in the previous pull request.
Used only when mean subtraction is used.
> Bessel's correction in PCA

- Examples/interruptible_pool.py
- Examples/pairwise_comparison.py
- turbustat/statistics/mvc/mvc.py
- turbustat/statistics/pspec_bispec/pspec_bispec.py
- turbustat/statistics/rfft_to_fft.py
- turbustat/statistics/vca_vcs/vca_vcs.py
- turbustat/statistics/wavelets/wavelet_transform.py
- turbustat/tests/test_rfft_to_fft.py
Switch to using numpy fft functions.
Most methods only require the absolute value of the fft, so memory can be saved by computing the rfft, then expanding to reproduce the output of fft.
Added tests for the rfft to fft output.
> Using numpy rfft to save memory

- .travis.yml
- Examples/analysis_pipeline.py
- Examples/effect_plots.py
- Examples/make_distance_plots.py
- Examples/make_obs_tables.py
- Examples/noise_validation.r
- Examples/signal_validation.r
- turbustat/analysis/comparison_plot.py
Brings the examples scripts for the paper up to date.
Testing on travis started to fail as a result of the newest numpy version. Seems to be an issue with skimage playing nicely with the new numpy. Some versions were altered for this reason. Hopefully, once the other packages have fixes, this can be removed. Support for python 2.6 will probably be dropped at that time.
> Updates to some examples scripts; Change numpy version for Travis

- turbustat/statistics/scf/scf.py
Added ability to get the 1D radially averaged SCF spectrum out.
> 1D spectrum for SCF

- setup.py
- turbustat/cube_tools/__init__.py
- turbustat/data_reduction/make_moments.py
- turbustat/statistics/dendrograms/dendro_stats.py
signal-id should not be a requirement at this stage. These changes make it an optional package to have.
I have also made astrodendro optional in case someone has no interest in running the dendrogram statistics.
> Optional pkgs

- turbustat/statistics/base_pspec2.py
- turbustat/statistics/base_statistic.py
- turbustat/statistics/delta_variance/delta_variance.py
- turbustat/statistics/mvc/mvc.py
- turbustat/statistics/pspec_bispec/pspec_bispec.py
- turbustat/statistics/scf/scf.py
- turbustat/statistics/vca_vcs/vca.py
- turbustat/statistics/wavelets/wavelet_transform.py
Corrects the use of angular spatial scales and frequencies in a number of methods.
All spatial scales and frequencies are given as `astropy.Quantity` objects in pixel units.
Plotting in angular units is enabled by setting `ang_units=True` in the `run` or `distance_metric` functions. The angular unit can be changed by altering `unit=u.deg` in `run` or `distance_metric`.
> Angular units

- turbustat/statistics/base_pspec2.py
- turbustat/statistics/lm_seg.py
`Lm_Seg` raises a more clear error message when the given break point is not finite.
The break point in the 2D Power spectrum methods assumes the value is in log-scale (ie. `log_break=True` by default).
> Ensure finite break points

- turbustat/analysis/comparison_plot.py
I'm unsure if this is a recent matplotlib change in how legends are handled, but extra legend labels were being added for plot commands without labels. This forces the fiducial-to-fiducial points to not show up in the legend.
> Force fiducial-to-fiducial plotting to not show up in the legend

- CHANGE.rst
- setup.py
- turbustat/__init__.py
- turbustat/statistics/pspec_bispec/pspec_bispec.py
The `nsamples` kwarg for `BiSpectrum_Distance` was not actually being passed. Now you can sample as much as you want!
Also fixes an issue when passing a FITS hdu to `BiSpectrum_Distance`, stops everything from being imported at the top level of the package, and register `check_deps` to check whether all package dependencies are installed (i.e., run `python setup.py check_deps`).
> Bispectrum nsamples input fix

- turbustat/statistics/vca_vcs/vcs.py
Force to use `self.header`, since `header` need not be set.
Make the VCS frequency axis labels more clear.
> VCS physical units bug

- README.md
- docs/install.rst
- turbustat/data_reduction/make_moments.py
Makes it (hopefully) more clear which packages are required for TurbuStat.
Since `spectral_cube` is optional, errors are raised when trying to use `Mask_and_Moments` when it hasn't been installed.
> Refining the required and optional packages

- CHANGE.rst
- turbustat/statistics/scf/scf.py
- turbustat/tests/test_scf.py
The indexing of the SCF surface was not updated to work with the non-integer shifts from #117.
Added tests for SCF for non-equal grids and non-integer shifts.
> SCF shifting

- turbustat/statistics/scf/scf.py
- turbustat/statistics/stats_utils.py
The Fourier shifting for SCF introduced in #117 fails with NaNs. This fixes that by shifting a NaN mask as well.
> NaN fourier shift

- CHANGE.rst
- turbustat/statistics/genus/genus.py
- turbustat/statistics/pdf/compare_pdf.py
- turbustat/statistics/pspec_bispec/pspec_bispec.py
Fixes errors when creating plots for PDF and bispectrum with data of different shapes.
Also added a common angular scale factor correction to the Genus distance normalization. Normalization is now effectively over a common angular area.
> Plotting fixes to PDF and bispectrum

- turbustat/data_reduction/make_moments.py
If none of our channels are good, then longestSequence will die with a fairly
uninformative error message. We can avoid this by doing the check for good
channels before the call to longestSequence, so that we get a more informative
error when we die.
> Move the good channels check

- CHANGE.rst
- turbustat/statistics/psds.py
- turbustat/tests/test_pspec.py
The indexing in `turbustat.statistics.psds.pspec` was swapped, creating issues whenever the 2D array did not have an equal shape.
> Fix indexing for azimuthal averaging

- CHANGE.rst
- turbustat/statistics/cramer/cramer.py
- turbustat/statistics/threeD_to_twoD.py
- turbustat/statistics/wrapping_function.py
- turbustat/tests/data/GetVals.py
- turbustat/tests/test_cramer.py
Added a normalization factor when computing the Cramer. The data matrices to calculate the statistics are now normalized by default to be within a range of 0 to 1. This ensures that constant offsets do not inflate the distance.
> Cramer normalization

- CHANGE.rst
- turbustat/statistics/dendrograms/dendro_stats.py
- turbustat/tests/test_dendro.py
Enables toggling whether the spatial dimensions of a cube/map are periodic.
By default, periodic boundaries are disabled.
In order to determine which axes are spatial dimensions, a FITS header is now required for `Dendrogram_Stats`.
> Periodic dendrogram boundaries

- .travis.yml
- turbustat/cube_tools/obs_cubes.py
- turbustat/cube_tools/sim_cubes.py
- turbustat/data_reduction/make_moments.py
- turbustat/tests/_testing_data.py
- turbustat/tests/test_make_moments.py
[signal-id](https://github.com/radio-astro-tools/signal-id) is optional, but the tests currently depend on it to calculate the approximate noise level in the unit testing data.
> Remove signal-id for tests

- .travis.yml
- CHANGE.rst
- turbustat/tests/test_load_beam.py
astropy dev no longer supports python 2. Drop it from the testing grid.
> Fix testing grid

- CHANGE.rst
- turbustat/statistics/base_pspec2.py
- turbustat/statistics/elliptical_powerlaw.py
- turbustat/tests/test_ellipplaw.py
The 2D elliptical power-law model can be difficult to fit in the isotropic case because `ellip=1` is at the edge of parameter space, making it hard to optimize. This PR adds the option to fix the ellip and theta parameters in the model for fitting an isotropic model. There is also a warning for all power-law methods to try fitting with fixed parameters when the ellipticity is close to 1.
Also added a radial weighting option when fitting a 2D power-law. This should make the fitted slope converge to the binned 1D slope by down-weighting points at large radii, where there are more samples to fit to. BUT this biases the fit parameters if the field is anisotropic. A warning is raised in this case.
> Fixing elliptical parameters in 2D model

- CHANGE.rst
- turbustat/statistics/vca_vcs/slice_thickness.py
- turbustat/statistics/vca_vcs/vca.py
- turbustat/statistics/vca_vcs/vcs.py
- turbustat/tests/test_vca.py
- turbustat/tests/test_vcs.py
The VCA technique relies on measuring the power-spectrum slope with different spectral channel widths. Prior to this PR, spectral downsampling smoothed then interpolated to a lower spectral resolution.  However, downsampling by averaging over an integer number of channels is closer to what has previously been used in the literature. This PR adds the latter method and makes it the default method for downsampling.
Downsampling has also been removed from the VCS, since this only acts to change the limits of the VCS extent.
> Downsample to change slice thickness

- turbustat/statistics/base_pspec2.py
- turbustat/statistics/delta_variance/delta_variance.py
- turbustat/statistics/mvc/mvc.py
- turbustat/statistics/pspec_bispec/bispec.py
- turbustat/statistics/pspec_bispec/pspec.py
- turbustat/statistics/scf/scf.py
- turbustat/statistics/vca_vcs/vca.py
- turbustat/statistics/vca_vcs/vcs.py
- turbustat/statistics/wavelets/wavelet_transform.py
Some of the plot changes from #191 broke the plotting in the distance metrics that were using the plotting routine from the statistic to overlay on the same axes. The statistics that create a new figure for the plot now grab the existing figure (if it exists) to overlay on the same axes.
> Fix plotting for distance metrics

- turbustat/statistics/pca/pca.py
- turbustat/statistics/pca/width_estimate.py
- turbustat/statistics/stats_utils.py
- turbustat/tests/test_pca.py
* Catch fit failures to the contour for the spatial scales
* Change the correction factor of the PCA fit index to Eq. 4.1 from Brunt & Heyer 2002
> PCA: catch fitting failures; alter correction factor

- .rtd-environment.yml
- CHANGE.rst
- README.md
- docs/conf.py
- docs/install.rst
- docs/tutorials/statistics/delta_variance_example.rst
- setup.py
- turbustat/statistics/convolve_wrapper.py
- turbustat/statistics/delta_variance/delta_variance.py
Fixing part of #207.
1. Require astropy >v2 to use the current  `convolve_fft` API.
2. Revise recommendations for NaN convolution settings, as recommended by @keflavich in #207.
3. Removed listing pandas as a dependency (#203).
> Delta-variance: Revise astropy convolution wrapper

- CHANGE.rst
- README.md
- docs/install.rst
- setup.py
You can install v1.0 via pip now. Make sure the docs say that.
Also, remove some unused code in `setup.py`.
> pip install in docs

- .travis.yml
- turbustat/statistics/pca/width_estimate.py
- turbustat/statistics/scf/scf.py
- turbustat/tests/_testing_data.py
`astropy.six.extern` was removed from the dev version of astropy.
> Remove six import from astropy

- turbustat/statistics/psds.py
- turbustat/statistics/vca_vcs/vca.py
All of the 1D pspec are azimuthal means over the 2D PSD. But a median or sigma-clipped mean could be useful for some data sets.
The function for the average can now be specified using:
```
import numpy as np
from turbustat.statistics import PowerSpectrum  # Or another pspec method
pspec = PowerSpectrum(hdu)  # Some already loaded FITS HDU
pspec.compute_pspec()
pspec.compute_radial_pspec(mean_func=np.nanmedian)
```
The default is to use `np.nanmean`.
Using the `run` function:
```
pspec.run(radial_pspec_kwargs={'mean_func': np.nanmedian})
```
> Change the "average" 1D pspec operation

- turbustat/statistics/vca_vcs/slice_thickness.py
VCA redefines a spectral cube just for downsampling, but this resets the `cube.allow_huge_operations` flag.
This can now be changed with:
```
from turbustat.statistics import VCA
vca = VCA(cube, channel_width=2, downsample_kwargs={"allow_huge_operations": True})
```
> Huge cube downsampling

- CHANGE.rst
- docs/conf.py
- docs/tutorials/code_for_examples.py
- docs/tutorials/metrics/code_for_metric_tutorials.py
- docs/tutorials/statistics/code_for_tutorials.py
- turbustat/statistics/base_pspec2.py
- turbustat/statistics/mvc/mvc.py
- turbustat/statistics/psds.py
- turbustat/statistics/pspec_bispec/bispec.py
- turbustat/statistics/pspec_bispec/pspec.py
- turbustat/statistics/vca_vcs/vca.py
`binned_statistic` in scipy 1.14 now checks for non-finite values. Previously, we were using `nanmean`/`nanstd` to avoid NaNs in the inputs.
This PR masks the input data before passing it to `binned_statistic`.
Also, I moved computing the beam power spectrum to its own function for the power spectrum-based methods.
> Fix binned statistics calls

- turbustat/statistics/tsallis/tsallis.py
As of scipy 1.7, explicit tests for the correctness of the Chisq test are included in `scipy.stats.chisquare`. We are only using the chisquare value and do not need the full test.
> Fix for Tsallis chi squared values with scipy 1.7

- turbustat/statistics/delta_variance/delta_variance.py
The fill behaviour has changed at some point in a recent astropy version. `DeltaVariance` previously forced filling with NaNs, which now fails when using `nan_treatment='fill'` (which makes sense, since it is supposed to be replacing the NaNs).
This PR updates to using 0. as the fill value when `nan_treatment='fill'`.
> Fix Delta Variance fill value

- turbustat/statistics/pspec_bispec/pspec.py
- turbustat/statistics/scf/scf.py
- turbustat/tests/test_pca.py
Addressing some issues that have been discovered during the 2021 ISM Summer school:
> Bug fixes from distance metric classes

- .github/workflows/main.yml
- .github/workflows/python-publish.yml
- pyproject.toml
- setup.cfg
- setup.py
- tox.ini
Tests started failing due to a mismatch in python 3.7 and dev requirements. This updates the testing versions to fix that.
> Update testing to drop 3.6 and add 3.9, 3.10

- docs/index.rst
- docs/install.rst
- turbustat/io/input_base.py
- turbustat/moments/_moment_errs.py
- turbustat/simulator/make_cube.py
- turbustat/simulator/tests/test_ppv.py
- turbustat/statistics/base_pspec2.py
- turbustat/statistics/genus/genus.py
This PR fixes various smaller bugs and makes running/saving the results of the Genus statistic easier.
Note that the "size" related issue was related to using the original image threshold values compared to the smoothed image. The default is to smooth the image by a 1 pixel wide Gaussian (this PR enables a no smoothing option), thereby lowering the standard deviation compared to the original image.
To fix this, we now record the mean and std for each smoothed/original image with `Genus.smoothed_means`, `Genus.smoothed_stds`. These correspond to the imaged smoothed by kernels defined in `Genus.smoothing_radii`. These mean/std values are what should be used to plot/fit the standardized values in a Genus curve (where standardized here is `zscore = (value - mean) / std`).
> Updates and fixes to Genus + numpy slice fixes

- .github/workflows/main.yml
- .github/workflows/python-publish.yml
- .gitignore
- setup.cfg
- tox.ini
- turbustat/moments/_moment_errs.py
- turbustat/statistics/base_pspec2.py
- turbustat/statistics/elliptical_powerlaw.py
- turbustat/statistics/mvc/mvc.py
- turbustat/statistics/pspec_bispec/bispec.py
- turbustat/statistics/pspec_bispec/pspec.py
- turbustat/statistics/scf/scf.py
- turbustat/statistics/vca_vcs/vca.py
- turbustat/statistics/wavelets/wavelet_transform.py
- turbustat/tests/test_ellipplaw.py
- turbustat/tests/test_pspec.py
- turbustat/tests/test_wavelet.py
The radial binning has a bias that we've recently found comparing against infilled maps of WISE. It's not yet clear where the issue is in the binning since the baseline tests against a known powerlaw image pass.
To alleviate this problem, this PR adds an option to fit a 1D model to the unbinned data, which returns fitted indices similar to the 2D elliptical power law fit (for an isotropic field).
Also incorporated as #244 and added testing for python 3.11. Dropped builds for python 3.7 following various dependencies.
> Add unbinned power spectrum fitting
